import React from 'react';
import CardSection from '../Cardsection';


export const Members = () => {
  const items = [
    { id: 1, title: "Bodhisattwa Sanghapriya", description: "FORMER TEAM CAPTAIN", image: "/images/BodhisattwaSanghapriya.jpg", year: 2000 },
    { id: 2, title: "Om Prakash Das", description: "FORMER CHIEF COMMUNICATION OFFICER", image: "/images/OmPrakashDas.jpg", year: 2000 },
    { id: 3, title: "Anurag Behera", description: "FORMER AVIONICS ARCHITECT", image: "/images/AnuragBehera.jpg", year: 2000 },
    { id: 4, title: "Anshuman Dikshit", description: "FORMER ELECTRONICS ARCHITECT", image: "/images/AnshumanDikshit.jpg", year: 2000 },
    { id: 5, title: "Dinesh Kumar Mohanty", description: "FORMER APP DEVELOPER", image: "/images/DineshKumarMohanty.jpg", year: 2000 },
    { id: 6, title: "Chandan Mandal", description: "FORMER WEB DEVELOPER", image: "/images/ChandanMandal.jpg", year: 2000 },
    { id: 7, title: "Joshit Mohanty", description: "FORMER MECHATRONICS LEAD", image: "/images/JoshitMohanty.jpg", year: 2000 },
    { id: 8, title: "Anil Pradhan", description: "FORMER DESIGN LEAD", image: "/images/AnilPradhan.jpg", year: 2000 },
    { id: 9, title: "Tapas Mahanta", description: "FORMER ELECTRONICS LEAD", image: "/images/TapasMahanta.jpg", year: 2000 },
    { id: 10, title: "Jaswasi Sahoo", description: "Team Captain HEAD OF PROPULSION", image: "/images/JaswasiSahoo.jpg", year: 2019 },
    { id: 11, title: "Apurwa Masook", description: "PUBLIC RELATION OFFICER (P.R.O.) GEOMATICS ANALYST", image: "/images/ApurwaMasook.jpg", year: 2019 },
    { id: 12, title: "Sudarshan Samal", description: "CHIEF TECHNOLOGY OFFICER (CTO) HEAD OF MECHATRONICS", image: "/images/SudarshanSamal.jpg", year: 2019 },
    { id: 13, title: "Sovan Panda", description: "CHIEF TECHNOLOGY OFFICER (CTO) HEAD OF MECHANICAL DESIGNS", image: "/images/SovanPanda.jpg", year: 2019 },
    { id: 14, title: "Ranjan Panda", description: "CHIEF DESIGN OFFICER HEAD OF INTERNAL AFFAIRS.", image: "/images/RanjanPanda.jpg", year: 2019 },
    { id: 15, title: "Tatwam Siddha Nanda", description: "CHIEF R&D MAVEN SCHOLAR", image: "/images/TatwamSiddhaNanda.jpg", year: 2019 },
    { id: 16, title: "Sahasransu Purohit", description: "CHIEF HR MANAGER STRUCTURAL REMOTE SENSING ANALYST", image: "/images/SahasransuPurohit.jpg", year: 2019 },
    { id: 17, title: "Sumit Kumar Sahu", description: "GENERAL MANAGER MODELLING EXPERT.", image: "/images/SumitKumarSahu.jpg", year: 2019 },
    { id: 18, title: "Pranaya Panda", description: "AERODYNAMIC ANALYST SIMULATION EXPERT", image: "/images/PranayaPanda.jpg", year: 2019 },
    { id: 19, title: "Rounak Agrawal", description: "PROGRAMMER", image: "/images/RounakAgrawal.jpg", year: 2019 },
    { id: 20, title: "Kunal Mittal", description: "HEAD OF COMMERCE DESIGN ANALYST.", image: "/images/KunalMittal.jpg", year: 2019 },
    { id: 21, title: "Rahul Nayak", description: "LEAD FLIGHT REGULATION", image: "/images/RahulNayak.jpg", year: 2019 },
    { id: 22, title: "Satyabrat Nath", description: "IGNITION EXPERT PYROTECHNIC ANALYST", image: "/images/SatyabratNath.jpg", year: 2019 },
    { id: 23, title: "Satyam Kumar", description: "LEAD FLIGHT CONTROL", image: "/images/SatyamKumar.jpg", year: 2019 },
    { id: 24, title: "Aditya Narayan Ojha", description: "LEAD AVIONICS ARCHITECT", image: "/images/AdityaNarayanOjha.jpg", year: 2019 },
    { id: 25, title: "Biswajeet Sahoo", description: "LEAD ELECTRONICS ARCHITECT", image: "/images/BiswajeetSahoo.jpg", year: 2019 },
    { id: 26, title: "Marshal Sahu", description: "LEAD PROGRAMMER", image: "/images/MarshalSahu.jpg", year: 2019 },
    { id: 27, title: "Subhasmita Panda", description: "Core Management Team Member at IIC", image: "/images/SUBHASMITAPANDA.jpg", year: 2019 },
    { id: 28, title: "SUKRITI KHANDELWAL", description: "Core Management Member", image: "/images/SUKRITIKHANDELWAL.jpg", year: 2019 },
    { id: 29, title: "SALONI DHAL", description: "Chief Content Officer", image: "/images/SALONIDHAL.jpg", year: 2019 },
    { id: 30, title: "MAMTA GUPTA", description: "Chief Workforce Manager", image: "/images/MAMTAGUPTA.jpg", year: 2019 },
    { id: 31, title: "SAILEY BALODIA", description: "Core Management Team Member at IIC.", image: "/images/SAILEYBALODIA.jpg", year: 2019 },
    { id: 32, title: "MAHIMA CHACHRA", description: "Core Management Team Member at IIC", image: "/images/MAHIMACHACHRA.jpg", year: 2019 },
    { id: 33, title: "Anshuman Pattanaik", description: "Secretary", image: "/images/Anshuman.jpg", year: 2020 },
    { id: 34, title: "Bibhudatta Panda", description: "Head of Mechanical Design", image: "/images/bibhudatta.jpg", year: 2020 },
    { id: 35, title: "Soumyajeet Mahapatra", description: "Head of Avionics.", image: "/images/soumyajeet.jpg", year: 2020 },
    { id: 36, title: "Amartya Mohanty", description: "Modeling Expert", image: "/images/Amartya.jpg", year: 2020 },
    { id: 37, title: "Markandeya Mohapatra", description: "Public Relation Officer & Head of Rocket Propulsion", image: "/images/markandeya.jpg", year: 2020 },
    { id: 38, title: "Prasant Kumar Sahoo", description: "Head Of Electronics", image: "/images/prasant.jpg", year: 2020 },
    { id: 39, title: "Sourav Kumar Sahoo", description: "Chief R&D", image: "/images/sourav.jpg", year: 2020 },
    { id: 40, title: "Lakshya Agrawal", description: "Head Programmer", image: "/images/lakshya.jpg", year: 2020 },
    { id: 41, title: "Rohit Tekriwal", description: "Management Associate", image: "/images/member41.jpeg", year: 2020 },
    { id: 42, title: "Rashmi Ranjan Pattnaik", description: "Head Of Structural Design", image: "/images/rashmi.jpg", year: 2020 },
    { id: 43, title: "Sritam Jena", description: "Core Management", image: "/images/sritam.jpg", year: 2020 },
    { id: 44, title: "Bhabya Mohanty", description: "Mechatronics Lead", image: "/images/bhabya.jpg", year: 2020 },
    { id: 45, title: "Saswat Nanda", description: "Core Management", image: "/images/saswat.jpg", year: 2020 },
    { id: 46, title: "Akash Kumar Mohanty", description: "Chief R&D", image: "/images/akash.jpg", year: 2020 },
    { id: 47, title: "Akash Kumar Patra", description: "Avionics Lead", image: "/images/akashpatra.jpg", year: 2020 },
    { id: 48, title: "Rohan Das", description: "Marketing Head", image: "/images/rohan.jpg", year: 2021 },
    { id: 49, title: "Rishabh Saraf", description: "Head of Technology", image: "/images/rishabh.jpg", year: 2021 },
    { id: 50, title: "Deepak Patra", description: "Digital Marketing", image: "/images/deepak.jpg", year: 2021 },
    { id: 51, title: "Pragati Sahu", description: "Chief Operation Officer", image: "/images/pragati.jpg", year: 2021 },
    { id: 52, title: "Kunal Kumar Dey", description: "Head of Content Management", image: "/images/kunal.jpg", year: 2021 },
    { id: 53, title: "Prateek Patra", description: "Digital Marketing", image: "/images/prateek.jpg", year: 2021 },
    { id: 54, title: "Ravi Kumar", description: "Mechanical Lead", image: "/images/ravi.jpg", year: 2021 },
    { id: 55, title: "Pramod Sahu", description: "Avionics Lead", image: "/images/pramod.jpg", year: 2021 },
    { id: 56, title: "Satyajit Mohapatra", description: "Mechanical Lead", image: "/images/satyajit.jpg", year: 2021 },
    { id: 57, title: "Ankita Pattnaik", description: "Core Management", image: "/images/ankita.jpg", year: 2021 },
    { id: 58, title: "Sonu Kumar", description: "Head of Research", image: "/images/sonu.jpg", year: 2021 },
    { id: 59, title: "Ritesh Mishra", description: "Head of Operations", image: "/images/ritesh.jpg", year: 2021 },
    { id: 60, title: "Subhranshu Sahu", description: "Head of Research", image: "/images/subhranshu.jpg", year: 2021 },
    { id: 61, title: "Anisha Mohapatra", description: "Lead Engineer", image: "/images/anisha.jpg", year: 2021 },
    { id: 62, title: "Amar Kumar", description: "Software Lead", image: "/images/amar.jpg", year: 2021 },
    { id: 63, title: "Pallavi Tripathi", description: "Head of Design", image: "/images/pallavi.jpg", year: 2021 },
    { id: 64, title: "Kajal Das", description: "Lead Engineer", image: "/images/kajal.jpg", year: 2021 },
    { id: 65, title: "Anmol Kumar", description: "Software Developer", image: "/images/anmol.jpg", year: 2021 },
    { id: 66, title: "Harsh Kumar", description: "Software Developer", image: "/images/harsh.jpg", year: 2021 },
    { id: 67, title: "Ajay Kumar", description: "Software Developer", image: "/images/ajay.jpg", year: 2021 },
    { id: 68, title: "Shivendra Kumar", description: "Head of Operations", image: "/images/shivendra.jpg", year: 2021 },
    { id: 69, title: "Himanshu Kumar", description: "Software Developer", image: "/images/himanshu.jpg", year: 2021 },
    { id: 70, title: "Bhupendra Kumar", description: "Software Developer", image: "/images/bhupendra.jpg", year: 2021 },
    { id: 71, title: "Shivam Kumar", description: "Software Developer", image: "/images/shivam.jpg", year: 2021 },
    { id: 72, title: "Satyendra Kumar", description: "Software Developer", image: "/images/satyendra.jpg", year: 2021 },
    { id: 73, title: "Vikash Kumar", description: "Software Developer", image: "/images/vikash.jpg", year: 2021 },
    { id: 74, title: "Saurav Kumar", description: "Software Developer", image: "/images/saurav.jpg", year: 2021 },
    { id: 75, title: "Abhishek Mishra", description: "Software Developer", image: "/images/abhishek.jpg", year: 2021 },
    { id: 76, title: "Ankur Sahu", description: "Software Developer", image: "/images/ankur.jpg", year: 2021 },
    { id: 77, title: "Bhanu Pratap", description: "Software Developer", image: "/images/bhanu.jpg", year: 2021 },
    { id: 78, title: "Vishal Gupta", description: "Software Developer", image: "/images/vishal.jpg", year: 2021 },
    { id: 79, title: "Satyam Raj", description: "Software Developer", image: "/images/satyam.jpg", year: 2021 },
    { id: 80, title: "Harish Kumar", description: "Software Developer", image: "/images/harish.jpg", year: 2021 },
    { id: 81, title: "Parag Gupta", description: "Software Developer", image: "/images/parag.jpg", year: 2021 },
    { id: 82, title: "Abhay Singh", description: "Software Developer", image: "/images/abhay.jpg", year: 2021 },
    { id: 83, title: "Shweta Patel", description: "Core Management", image: "/images/swetaparna.jpg", year: 2021 },
  ];

  return (
    <div className="flex justify-center items-center bg-primary min-h-screen">
      <CardSection items={items} />
    </div>
  );
};

