
import React from 'react';
import CardSection from '../projectcardsection'; // Ensure the correct import path

const Page = () => {

  const cardData = [
    { title: "VSLV", description: "India’s First Multipurpose Student Rocketry Mission- Launching our own satellite Launching vehicle to a height of 50+ km and deploying a Pico-sat which will monitor the Hirakud Dam along with these it can be used in different applications like Cloud Seeding, short range guided missile.", image: "/images/vslvlogofinal.png" },
    { title: "Krishi Sevak", description: "The Hand-Operated Rice Transplanter is a lightweight, easy to use and low cost machine. It is pedal operated and powered by hands. It has very low maintenance, and does not require any fuel. The parts are made from materials which can be easily obtained from any bicycle shop.", image: "/images/RicePlanterd.jpg" },
    { title: "Aria", description: "Air Quality Monitoring System- By integrating series of gas sensors modules with a microcontroller board to monitor the real time gas readings in PPM. A humidity and temperature sensor are also used to measure the surrounding temperature. A copy of this data is shown in a mini LCD display monitor.", image: "/images/ARIAd.jpg" },
    { title: "3D Aerial Mapping", description: "Using unmanned vehicle photogrammetric data acquisition of a given region to be surveyed, using brushless camera gimbal with motor controller. The Data is processed and rendered in advanced 3d Simulation Software. Project is being currently used for volumetric analysis of coal.", image: "/images/3darieald.jpg" },
    { title: "Carbon scrubbing and automation", description: "Using fumed silica impregnated with polyethylenimine in the inner walls of the chimney, which absorbs CO2 and storing them in absorber column pack. As the pack reaches the saturation point, then a pressure sensor transmits the message to extract required CO2 from it. It is carried out through a stream of superheated steam at around 120°C is passed through it.", image: "/images/Carbond.jpg" },
    { title: "Smart parking solution", description: "By using a network of optical detectors, the sensors will transmit real time data regarding the availability of parking slots. It will be integrated using IoT, and Google Maps API to display status of the parking spaces of the chosen destination, in an IoT based Android app. The Parking spaces can be pre-booked for the given time interval.", image: "/images/smartd.jpg" },
    { title: "Anecure", description: "It is a non-invasive, inexpensive, portable, low cost Electronic Device for monitoring of an individual’s Haemoglobin count, heartbeat count and glucose level. It works on the principle of absorption of a particular wavelength of light, i.e. spectroscopy. For effective diagnosis. The test can be made accurately and quickly.", image: "/images/800px_COLOURBOX3752702.jpg" },
    { title: "Sineocure", description: "Breast Cancer Detection device for early detection of Breast Cancer. It is a point of care device which uses thermal imaging incorporating it with AI and IOT for detection of cancer.", image: "/images/breast-cancer-awareness-3914243_960_720.png" },
    { title: "Multi utility torch", description: "It is a unique torch light which possess different kind of features like AM/FM radio, Soil Testing, Water Quality Testing in a single torch light. It is a low cost multi utility torch light for rural India.", image: "/images/purepng.com-torch-lightlamp-light-object-torch-night-electronic-flashlight-941524646997lkwds.png" },
    { title: "Pro-Dis", description: "An Augmented Reality product to make any transparent surface an interactive one with sun readable capability has a widespread application in field of aerospace, advertisement, process industries.", image: "/images/multi-touch-switchable-smart-glass-screens-product-launches.jpg" },
    { title: "R.A.P.I.D", description: "This device is used to detect the potholes in the roads and is also helpful to predict the possible areas where portholes can be created.", image: "/images/porthole.jpg" },
    { title: "Universal Language Translator", description: "Do you want to travel to another country and you do not know the language? Are you translating a document and you do not know what does each word mean? If you are looking for an easy way to translate from one language to another, All Language Translator is what you need. This Light-weight language translator is to translate between multiple languages. No more communication problem or language problem with this.", image: "/images/utl.jpg" },
    { title: "Fit-Foot", description: "Antibacterial Deodorizing Shoes that removes the bad odour and prevent the creation of sweat inside the shoes. It can be reused and the ability to give fragrance to the environment enhances its utility.", image: "/images/shoe-odour-526X544.png" },
    { title: "Intravenous Infusion Monitoring", description: "Traditional way of infusion flow doesn’t that much accurate. But this smart kit is a multipurpose integrated device which control the infusion flow as per the requirement as well as preventing the dosing errors.", image: "/images/infusion.jpg" },
    { title: "Iris Authenticator", description: "Universal Authentication is a method for verifying the identity of users on a specific website without asking for the same identification every time the user moves from one site to the other. The user need not to input his/her security details again every time a new mode is encountered. To enter into the sites the only thing to do is just scan your iris with your camera. It takes the required data like the intricate structure of your iris and stores it in the database and when you want to access your account the second time, it just searches for the required match if found it gives access.", image: "/images/iris.jpg" },
    { title: "Portable Soil Monitoring System", description: "The project will benefit farmers by letting them know the amount of minerals present in the soil. As now-a-days farmers don’t know what is the composition of minerals in their soil, they put fertilizers in a haphazard manner. So we use the spectroscopy technology to know the composition of minerals present in the soil, thus allowing them use fertilizers in a well planned manner that will enhance the quality of soil. We made a sample solution of soil to be tested, and then we placed it in between two convex lenses. The source of light ray is an LED bulb that illuminates and thus producing light rays. The light rays after passing through the convex lens converges at other end, i.e. at camera thus allowing to know the intensity and hence composition of minerals.", image: "/images/soil.jpg" },
    { title: "High end access control system", description: "The prototype uses a combination of Body Mass, specific RFID, Biometric(Fingerprint) and Password. Based on these credentionals it allows access to authorized person. -The prototype is a microcontroller based login system integrated with modules to fetch access parameters. -In case of unautherioze access the concerned authority will alerted by notification at cell.", image: "/images/Access-Control.jpg" },
    { title: "RO water purifier", description: "In the RO process there is a lot of wastewater but in our model, we are trying to minimise the waste by using both osmosis and the reverse osmosis process. Here first the supply water( mainly tap water) undergoes RO and we get pure water. Then the wastewater goes under osmosis with the charcoal treated tap water resulting in a decrease in impurity concentration of the wastewater. After this water undergoes RO with pure water to obtain pure water. And again the wastewater undergoes the previously mentioned cyclic process which causes the zero wastage of water.", image: "/images/ro.jpg" },
    { title: "Fuel Defender", description: "Generally oil carrying tanks in India are defenseless and security-less which means there is a high probability of oil robbery. Here we are trying to enhance the security of the adding some features which consists of 3 things (i) pressure and weight measuring device, (ii)security pass code system which can be changed according to time and (iii) alarming system. With the password the tank can't be opened and if any other measures taken there will be a pressure and weight variance which will activate the alarming system. The alarming system will inform both sender and receiver side as well as the police. So the security system has 2 step verification which won't allow any robbery to take place.", image: "/images/OIKL.png" },
    { title: "Inspection Optimizer", description: "Nowadays inspection is a clamorous activity to ensure customer satisfaction. But that is processed manually and rely on the judgmental experience of the experts. It gives less accuracy and requires extra manpower. To overcome this we are here with an idea which can give the extremely satisfactory result on inspection with the help of Artifical Intelligence and image processing. It requires less manpower and time.", image: "/images/OPTIM.png" },
    { title: "Smart water treatment", description: "Kitchen waste water can be treated with a simple oil and grease trap and a planted filter for reuse as garden water. The first thing to do is to trap the oil and grease which can be taken out occasionally and put into a compost heap. The food material is also allowed to settle down and separated from the rest of the water . By applying screening we can remove the other particles present in the water. Other process added to it is sedimentation , oil separator etc . , This remaining water is oxygenated using a small aquarium bubbler. It also consumes less than a half unit of energy every day. About 100 litres to 120 litres of water can be treated and used to water the pots and the garden.", image: "/images/smart_city_waste_water_treatment_leakage_broke-512.png" },
    { title: "Bike crash detection", description: "The prototype consists of a mobile application and detection box which will be fixed with the bike. The box and the mobile application will be connected via wi-fi. In the application we will use the GPS locating and messaging facility of the phone, which will be used to inform the selected contact and nearby hospital about the accident. The function of the detection box will be to sense an accident and will send a signal to the mobile of the user,which will ultimately send a distress signsl to the 2 trusted contact choosen by the user and the nearby hospital along with the location of accident.", image: "/images/Depositphotos_22235443_m-2015-cropped.jpg" },
    { title: "Life Saving Buoy", description: "The proposed solution for the loss of lives as a result of drowning is a self-propelled lifesaving buoy. It is a lifesaving buoy that can drive itself around the water by remote control. The buoy doesn’t require any other individual to get into the water and put the person’s life in the danger in order to way to save one more life. It can be remotely guided by an individual safely from land. The self-propelled lifebuoy can be then driven to the drowning victim and he/she can grab the lifebuoy to float on the surface. Then it can be driven back to the nearest safe ground and the victim can be saved.", image: "/images/lifebuoy_PNG42.png" },
    { title: "Desalination of water", description: "We will use a specially designed chamber where we can reduce the chamber pressure so that saline water inside it can evaporate at low temperature. Precipitated salts will be removed from the chamber and can be used for business purpose. It is a low cost product and specially designed for rural India.", image: "/images/png-transparent-water-desalination-technology-cimne-business-water.png" },
    { title: "Ghee Making Machine", description: "Mechanization of ghee machine using a unique 3 stage scraped heat exchanger mainly focuses on the heat clarification and increasing the product quality with continuous process.", image: "/images/palm-oil-butter-ghee-making-machine-plant.png_640x640.jpg" },
    { title: "Broom making machine", description: "DPeople from different places migrate to make a living making brooms. They leave their native place and come to stay in temporary structures, make brooms and sell them. However the earnings do not fulfil their basic needs. Objective: The objective is to make a device/tool to assist the broom making process to 1. Increase the safety by making the process less injury prone. 2. Reduce the manual effort in beating the leaves on an assembly of nails. 3. Reduce the time required to produce brooms. 4. Make it easily transportable. 5. It can be easily disassembled/ assembled. It takes maximum 5 minutes to assemble all the parts . 6. When not in use the cycle can be used as a normal bicycle.", image: "/images/broom-making_equipment_-_joseph_allen_skinner_museum_-_dsc07885-1_red.jpg" },
    { title: "Farmasecure", description: "An app to provide complete user satisfaction to the farmer in their local language and they will communicate with other farmers for solutions . And a smart locomotive refrigerater integrated to provide product to the destined places and providing fixed price for their product and the whole app is under developement and we have already developed the user interface.", image: "/images/illustration-of-a-farmer-with-a-rake-in-front-of-a-farm-house-vector.jpg" },
    
  ];

  return (

 <div className="container mx-auto max-w-screen-xl my-0"> {/*resovled css conflict by removing mx-1 */}

  {/* */}
  <CardSection cardData={cardData} />
</div>

  );
};

export default Page;
